name: 'Netlify Preview Deploy'
run-name: ${{ github.actor }} is deploying the site
on:
  push:
    branches: 
      - main
jobs:
  deploy:
    # name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}